packages/commons/README.md
This PR initializes the `/packages/commons` directory that will contain the `Deque.AxeCore.Commons` package with a skeleton `README.md` file.
Part of #7
=> feat(commons): create initial commons package directory and README.md

.gitignore, Deque.AxeCore.sln, packages/selenium/src/AxeBuilderOptions.cs, packages/selenium/src/Deque.AxeCore.Selenium.csproj, packages/selenium/src/EmbeddedResourceAxeProvider.cs, packages/selenium/src/ExternalAxeScriptProvider.cs, packages/selenium/src/FileAxeScriptProvider.cs, packages/selenium/src/IAxeScriptProvider.cs, packages/selenium/src/WebDriverInjectorExtensions.cs
This PR wires up the selenium project to make use of the commons project. It includes:
* Adds a project reference from selenium csproj to commons
* Updates the selenium code to use a single type from commons (`IAxeScriptProvider`) instead of itself to verify that the wiring is working correctly
* Adds the selenium project (and its test project) to the repo-level sln file
* When I tested that this opened reasonably in Visual Studio, I found that `.gitignore` was missing an entry for the `.vs/` folder that Visual Studio uses for temp files, so I added that while I was here
To verify, run `dotnet test` from the root of the repo - it should pick up all 4 projects and successfully run 6 instances of tests (3x target framework for each of the 2 test projects)
Out of scope (to be handled in …
=> feat(selenium): add reference from selenium project to commons project

.github/workflows/build-and-test.yml, .github/workflows/create-release.yml, .github/workflows/publish-canary.yml, .github/workflows/publish-nuget-packages.yml, .github/workflows/publish-production.yml, .github/workflows/pull-request.yml, .github/workflows/sync-master-develop.yml
This PR implements the second half of what was originally #34. It is modeled after the workflows in https://github.com/dequelabs/axe-core-maven-html, https://github.com/dequelabs/axe-core-npm, https://github.com/dequelabs/axe-core, and off discussion with @AdnoC about how certain internal Deque .NET builds work.
For now, the final `dotnet nuget push` steps that do the literal publishing to nuget are implemented in "dry run" mode, since there isn't a NuGet account established yet to do the actual release. Once that's done (tracked by #38), the end of `publish-nuget-packages.yml` should be updated accordingly.
It is intended to work very similarly to existing build/release automation in the other similar libraries, except with everything based on GitHub actions instead of going through …
=> ci: add publish/release workflows in dry-run mode

.github/workflows/build-and-test.yml, packages/commons/test/Deque.AxeCore.Commons.Test.csproj, packages/playwright/test/AxeContentEmbedderTests.cs, packages/playwright/test/Deque.AxeCore.Playwright.Test.csproj, packages/playwright/test/IntegrationTests.cs, packages/selenium/test/AxeResultTargetConverterTest.cs, packages/selenium/test/Deque.AxeCore.Selenium.Test.csproj, packages/selenium/test/IntegrationTests.cs
This PR standardizes the assorted test projects such that they run and produce output in a reliable, actionable format. Specifically:
* It migrates the playwright test project from MSTest to NUnit
* It updates all test dependencies to consistent, latest versions
* It fixes a few new NUnit warnings suggesting migration from `Assert.IsEqual(expected, actual)` type syntax to `Assert.That(actual, Is.EqualTo(expected))` syntax
* It adds a new dependency on GitHubActionsTestLogger from each test project to produce actionable GitHub Actions output
* It standardizes the test results directory on `TestResults/$(TargetFramework)` to avoid result files for the different frameworks from stomping on each other
* It updates the PR build `--logger` config to:
* use a more minimal console logger …
=> test: standardize test projects on nunit with consistent output formats

packages/selenium/src/Deque.AxeCore.Selenium.csproj
Removes an obsolete dependency on the `HtmlAgilityPack` package. This dependency was part of the HTML reporting functionality removed in #40 , but that PR missed removing the `PackageReference`.
Closes Issue: n/a
=> fix: remove unnecessary dep from selenium package on HtmlAgilityPack

CONTRIBUTING.md, packages/playwright/test/IntegrationTests.cs, packages/selenium/test/IntegrationTests.cs
Before this PR, the behavior for choosing whether to use headless browsers (faster, less intrusive) vs headful browsers (helps debug some specific types of issues) differed between the Selenium and Playwright test projects:
* Playwright used headless browsers in "release" configuration (what PR/release builds use by default) and headful in "debug" builds (what `dotnet test` uses by default)
* Selenium always used headless
Neither of these were ideal; in most cases, you want the faster/less intrusive/more-consistent-with-PR-builds version when running `dotnet test`, but it's nice to be able to opt-in to headful testing for debugging issues where you want to see page state within a breakpoint.
This PR updates the logic for both projects to run headless by default regardless of build …
=> test: standardize on HEADED env var for headful browser testing

packages/selenium/README.md, packages/selenium/src/AxeBuilder.cs, packages/selenium/test/AxeBuilderTest.cs
This PR removes the already-deprecated `Options` property from the selenium package's `AxeBuilder`. This has been deprecated for some time and we're making breaking changes anyway with the new release, now is a good time to remove it.
Closes Issue: n/a
BREAKING CHANGE: removes a (already-deprecated) property
=> feat(selenium)!: remove deprecated Options property from AxeBuilder

packages/commons/src/AxeResult.cs, packages/commons/src/AxeResultCheck.cs, packages/commons/src/AxeResultItem.cs, packages/commons/src/AxeResultNode.cs, packages/commons/src/AxeResultRelatedNode.cs, packages/commons/src/AxeRunContext.cs, packages/commons/src/AxeTestEnvironment.cs, packages/commons/src/AxeTestRunner.cs
This PR adds comments to the public types in commons package. Most of the descriptions were taken from the [axe API documentation](https://www.deque.com/axe/core-documentation/api-documentation/).
Other references: 
* WindowWidth: https://developer.mozilla.org/en-US/docs/Web/API/Window/innerWidth
* WindowHeight: https://developer.mozilla.org/en-US/docs/Web/API/Window/innerHeight
* OrientationAngle: https://developer.mozilla.org/en-US/docs/Web/API/ScreenOrientation/angle and https://w3c.github.io/screen-orientation/#dom-screenorientation-angle
Closes Issue: #18 
Closes Issue: #60
=> feat(commons): Add doc comments to commons typings

packages/playwright/src/Deque.AxeCore.Playwright.csproj
#39 modified the versioning strategy for the assorted packages such that a comment in `Deque.AxeCore.Playwright.csproj` became outdated, but missed updating the comment. This PR corrects the comment to match the actual versioning expectations, consistent with the other .csproj files.
=> chore: correct outdated comment in Playwright csproj

packages/selenium/README.md, packages/selenium/src/AxeBuilder.cs
This PR adds API documentation for the new public `UseLegacyMode` API to the README docs for the selenium package. The docs are based on the similar docs for [`@axe-core/playwright`'s `setLegacyMode` API](https://github.com/dequelabs/axe-core-npm/tree/develop/packages/playwright#axebuildersetlegacymodelegacymode-boolean--true).
While I was writing the code sample for the docs, I noticed that the default value for the new API (previously `false`) made for the following confusing behavior:
```csharp
// Looks intuitively like it would be using legacy mode, but actually isn't
AxeResult axeResult = new AxeBuilder(webDriver)
.UseLegacyMode()
.Analyze();
```
This PR updates the default value on `UseLegacyMode`'s parameter to `true` to make this interaction less confusing and for consistency with …
=> feat(selenium): fix default value and add API docs for new UseLegacyMode API

packages/selenium/README.md
This PR adds a new section to the selenium README to act as a migration guide from `Selenium.Axe` to `Deque.AxeCore.Selenium`. It is intended to include notes for all the breaking changes we've made since pulling in Selenium.Axe (particularly, from #63, #59, #58) - it would be helpful if reviewer(s) could double check the list of closed PRs for any I might have missed.
Closes Issue: #16
=> docs: add migration guide to selenium readme

packages/commons/README.md
Updates the reference to `axe-core` in the License section to link the the relevant repo
Closes Issue:
=> docs: update axe-core link in commons README.md

packages/commons/src/AxeResult.cs, packages/commons/test/AxeResultTest.cs, packages/selenium/README.md, packages/selenium/test/RunPartial/FinishRunTests.cs
This PR removes the `AxeResult.Error` property that was previously used to indicate a very select few types of errors (exceptions emitted from runLegacy.js or finishRun.js, but only against WebDrivers that didn't normalize those errors as JavaScriptExceptions already) and replaces it with exception-throwing. From a user's perspective, this means that if a scan emits an exception (should be rare anyway), it will propagate as a test failure instead of (probably) ending up silently ignored.
I also added a basic `AxeResult` unit test as part of writing a test for the new functionality. While writing basic unit tests I noticed that the default `ToString` behavior `AxeResult` is currently using is pretty user-unfriendly, but I felt that should be addressed in a separate PR, so I omitted that …
=> feat: replace AxeResult.Error property with exceptions

.github/scripts/prepare_release.sh
This PR adds the `prepare_release.sh` script that was present in #34 and intended to be included in #39. It is invoked from L25 of the `create-release.yml` workflow that was merged as part of #39.
Closes Issue: n/a
=> chore: re-add release script accidentally omitted from #39

packages/playwright/README.md
Updates a minor typo in the README.md, instructs on how to migrate from `Playwright.axe`, and adds description of relelvant breaking changes for said migration
Closes Issue: #21
=> docs: adding Playwright migration guide

packages/commons/src/AxeJsonSerializerSettings.cs, packages/commons/src/AxeResult.cs, packages/commons/src/AxeResultItem.cs, packages/commons/test/AxeResultItemTest.cs, packages/commons/test/AxeResultTest.cs, packages/commons/test/AxeRunOptionsTest.cs, packages/selenium/src/AxeBuilder.cs, packages/selenium/test/AxeBuilderLegacyTest.cs, packages/selenium/test/AxeBuilderTest.cs, packages/selenium/test/RunPartial/FinishRunTests.cs
This PR adds in a basic ToString implementation for `AxeResult` and `AxeResultItem` that just uses `JsonConvert.SerializeObject`.
The motivation for this is that these types are likely to be used in users' test assertions; when an assertion related to them fails, we want the test output to be actionable.
I wanted to reuse the same `JsonSerializerSettings` as everywhere else in the Selenium package, so I extracted it out of `AxeBuilder` (and several tests that repeated bits of it) into a `AxeJsonSerializerSettings` static class in the commons package. I think this is a better home for the serializer settings anyway, since they're tightly coupled to the implementation of the types.
The test addition will have a merge conflict to resolve with #74, which adds overlapping unit tests that share …
=> feat: implement AxeResult.ToString based on JsonConvert

packages/commons/src/AxeResult.cs, packages/commons/src/AxeTestEngine.cs, packages/commons/test/AxeResultTest.cs, packages/selenium/README.md, packages/selenium/test/RunPartial/AnalyzeTests.cs, packages/selenium/test/RunPartial/FinishRunTests.cs
`AxeResult` currently contains `TestEngineName` and `TestEngineVersion` properties. This PR creates an AxeTestEngine class to better represent the structure of the Axe results data, which looks like
```
"testEngine": {
"name": "axe-core",
"version": "3.4.1"
}
```
Closes Issue: n/a
=> feat(commons): add AxeTestEngine

.github/workflows/publish-canary.yml
Closes: https://github.com/dequelabs/axe-core-nuget/issues/127
=> ci: add release branch check to publish-canary.yml

packages/playwright/README.md
The Playwright package README was incorrectly referencing the Selenium NuGet package.
Closes Issue:
=> docs: Reference to Selenium Nuget packages in Playwright README

.github/workflows/auto-patch-release.yml, .github/workflows/build-and-test.yml, .github/workflows/create-release-candidate.yml, .github/workflows/create-release.yml, .github/workflows/publish-nuget-packages.yml, .github/workflows/publish-production.yml, .github/workflows/semantic-pr-footer.yml, .github/workflows/semantic-pr-title.yml, .github/workflows/sync-master-develop.yml, .github/workflows/update-axe-core.yml
Reviewer note: some of this repo's GHA setup is based on reusable workflows, which support setting job timeouts only on the reused inner workflow (eg, `build-and-test.yml`, `publish-nuget-packages.yml`) and not the containing workflows; that's why it looks like some jobs are omitted (eg, `pull-request.yml`)
Closes: #139
=> chore: add timeouts to GitHub Actions jobs

packages/playwright/README.md, packages/playwright/src/LocatorExtensions.cs, packages/playwright/test/IntegrationTests.cs
A user in our community slack reported having some trouble with our readme example. I went through all the README examples and updated some cases that weren't updated properly when migrating the original library code. I added integration tests for the more complex samples to verify that they run as-written.
Closes: #143
=> docs(playwright): fix broken readme examples
