dequelabs/axe-core-nuget

- .github/workflow/semantic-pr-title.yml
> ci: add semantic pr title workflow

- packages/commons/src/package-lock.json
- packages/commons/src/package.json
> feat: upgrade to use axe-core@4.5.0

- packages/commons/src/package-lock.json
- packages/commons/src/package.json
- packages/selenium/test/RunPartial/UseLegacyTests.cs
> feat: update axe-core to v4.7.1

- packages/playwright/test/Deque.AxeCore.Playwright.Test.csproj
- packages/playwright/test/TestServer.cs
Closes Issue: https://github.com/dequelabs/axe-core-nuget/issues/85
> test: fix build on non-windows platforms

- .github/scripts/prepare_release.sh
- .github/workflows/auto-patch-release.yml
- package.json
Closes Issue: https://github.com/dequelabs/axe-api-team/issues/333
> ci: auto patch-release every 2 weeks

- .github/workflows/auto-patch-release.yml
> ci: run auto-patch on thursdays

- CONTRIBUTING.md
- README.md
- packages/playwright/README.md
- packages/selenium/README.md
Closes Issue: https://github.com/dequelabs/axe-core-nuget/issues/98
> docs: update README for idiomatic usage

- .github/workflows/auto-patch-release.yml
Test PR: https://github.com/dequelabs/axe-core-nuget/pull/95
Test Issue: https://github.com/dequelabs/axe-core-nuget/issues/94
Conditional checks were tested in a personal repo: https://github.com/AdnoC/action-test/actions/workflows/push-and-dispatch.yml
https://github.com/dequelabs/axe-api-team/issues/342
> ci: enable manual run of patch release

- .github/workflows/create-release.yml
> ci: create-pull-request needs contents permission

- .github/workflows/update-axe-core.yml
Test PR: https://github.com/dequelabs/axe-core-nuget/pull/109
Test run: https://github.com/dequelabs/axe-core-nuget/actions/runs/6122406033/job/16618088442
> ci: add axe-core update workflow

- .github/workflows/auto-patch-release.yml
> CI: Remove schedule from auto-patch-release.yml

- packages/commons/src/package-lock.json
- packages/commons/src/package.json
Closes Issue: https://github.com/dequelabs/axe-core-nuget/issues/114
> fix(commons): pin axe-core version to accept patch updates only

- packages/commons/test/package-lock.json
- packages/selenium/src/AxeBuilder.cs
- packages/selenium/src/Deque.AxeCore.Selenium.csproj
- packages/selenium/src/Resources/finishRun.js
- packages/selenium/src/Resources/storeChunk.js
- packages/selenium/test/AxeBuilderTest.cs
- packages/selenium/test/Deque.AxeCore.Selenium.Test.csproj
- packages/selenium/test/RunPartial/AnalyzeTests.cs
- packages/selenium/test/RunPartial/TestBase.cs
Closes: https://github.com/dequelabs/axe-core-nuget/issues/80
> fix: work with extremely large results

- .github/workflows/sync-master-develop.yml
> ci: fix sync master workflow

- .github/workflows/publish-production.yml
Closes: https://github.com/dequelabs/axe-core-nuget/issues/158
no qa required
> ci: add release target branch when releasing

- .github/workflows/sync-master-develop.yml
should fix this https://github.com/dequelabs/axe-core-nuget/actions/runs/7903090464
no qa required
> ci: update `action-sync-branches` action

- packages/commons/test/package-lock.json
- packages/commons/test/package.json
Fixes the broken lazy load iframe tests.
Ref: https://github.com/dequelabs/axe-core-npm/pull/1052
No QA needed.
> chore: update test-fixtures to fix lazy load

- .github/workflows/sync-master-develop.yml
> ci: update action-sync action to v1

- .github/workflows/publish-nuget-packages.yml
- .github/workflows/publish-production.yml
- .github/workflows/update-axe-core.yml
> ci: update actions to latest

- .github/workflows/build-and-test.yml
- .github/workflows/publish-nuget-packages.yml
- .github/workflows/publish-production.yml
- .github/workflows/sync-master-develop.yml
- .github/workflows/update-axe-core.yml
- CHANGELOG.md
- package.json
- packages/commons/src/Deque.AxeCore.Commons.csproj
- packages/commons/src/package-lock.json
- packages/commons/src/package.json
- packages/playwright/src/Deque.AxeCore.Playwright.csproj
- packages/selenium/src/Deque.AxeCore.Selenium.csproj
> Release 4.10.1
